### ISSUE TITLE
Phone Input Max Length

### ISSUE THREAD

**Issue by wafda** [MuhammedAlmaz/React-Native-INTL-Phone-Input#13]
Please provide option to add custom phone input max length, since several country has different max length of phone number

**Comment by MSumairQureshi** [comment]
You can change phone length of each country by changing mask property (mask: '999 9999')
inside Countries.js

Location of this file:  node_modules\react-native-intl-phone-input\src

![image](https://user-images.githubusercontent.com/65311843/83625562-c82b8d00-a59c-11ea-9c1a-2d26351fc939.png)

**Comment by MuhammedAlmaz** [comment]
Which country is incorrect mask? @wafda

**Comment by MSumairQureshi** [comment]
Saudi Arab is also incorrect.
It should be mask: 99 999 9999

**Comment by MuhammedAlmaz** [comment]
Is there any list about the country mask information ?

**Comment by kmayatwal** [comment]
india is also incorrect.
it should be mask: 99999 99999

**Comment by kmayatwal** [comment]
> Is there any list about the country mask information ?

you can check all the information here.
https://en.wikipedia.org/wiki/List_of_mobile_telephone_prefixes_by_country

**Comment by FarazPatankar** [comment]
@MuhammedAlmaz I am curious if you're considering fixing this internally or are open to PRs for the same. There are several issues and because of that, we can't use the library to verify the number before letting the user submit it.

Let me know.

**Comment by SirPhemmiey** [comment]
@FarazPatankar , is there any update on this, please?

**Comment by MuhammedAlmaz** [comment]
@FarazPatankar fix the issue i merge the PRs on project. I am open the new developings.

**Comment by FarazPatankar** [comment]
@MuhammedAlmaz Sounds good. Any chance you could do a new release with some of the fixes for input length?
