### ISSUE TITLE
ReferenceError: Can't find variable: lang

### ISSUE THREAD

**Issue by Hudson784** [MuhammedAlmaz/React-Native-INTL-Phone-Input#18]
After installing the package, i attempted to use the component 
 
<IntlPhoneInput
          defaultCountry="VC"
          lang="EN"
          onChangeText={({ dialCode, unmaskedPhoneNumber }) =>
            setPhoneNumber(dialCode + unmaskedPhoneNumber)
          }
        />

To reproduce the issue: 

Install the package 
Attempt to change the country's flag by searching for country's name

Error: 

ReferenceError: Can't find variable: lang

**Comment by MuhammedAlmaz** [comment]
this issue solved at version of "**1.2.18**"
