### ISSUE TITLE
Warning: Failed prop type: Invalid prop 'autoCompleteType'  of value `false` supplied to TextInput 

### ISSUE THREAD

**Issue by Hudson784** [MuhammedAlmaz/React-Native-INTL-Phone-Input#19]
Reproduce by installing the package and using the component as stated in the documentation. 

Temporary solution is to go inside the node_modules folder ->  IntlPhoneInput.js 

Change it from false to "tel"  or a preferred choice.  If you install any other packages it'll revert that change made.

**Comment by MuhammedAlmaz** [comment]
Bug fixed
