### ISSUE TITLE
How to show Default Value(Mobile no.)

### ISSUE THREAD

**Issue by abhishekdarteweb** [MuhammedAlmaz/React-Native-INTL-Phone-Input#20]
Hello,

You developed a great plugin. I am using it but  i have an issue
How can we show default mobile no. in textbox? 
Please Help!

**Comment by kmayatwal** [comment]
@abhishekdarteweb 
you can do it using 
`<IntlPhoneInput onChangeText={this.onChangeText} defaultCountry="EN" placeholder="99999 99999"/>`

you have to just pass the placeholder prop in the component and that can show you the default mobile number.

**Comment by abhishekdarteweb** [comment]
Thanks for reply but i want to use IntlPhoneInput in edit mode and i'm fetching mobile no. from database then how can i?

**Comment by kmayatwal** [comment]
can you please share the code? so we can understand it better.

**Comment by MuhammedAlmaz** [comment]
@kmayatwal is true. Can u share your code. What do you want ?
`<IntlPhoneInput ref={(ref) => this.phoneInput = ref} />`

`onDataLoaded=(data)=>this.phoneInput.onChangeText(data.phoneNumber);`

You can try it. Use the ref variable if you want to change text data.

**Comment by SirPhemmiey** [comment]
@MuhammedAlmaz how can i use this in a functional component?
