### ISSUE TITLE
How can i use other <TextInput> props?

### ISSUE THREAD

**Issue by SirPhemmiey** [MuhammedAlmaz/React-Native-INTL-Phone-Input#23]
I want to use some normal TextInput props functions like onBlur, onFocus, etc. How can i do this, please? I thought the component should inherit all props of the normal TextInput. Please let me know how i can do this. Thanks

**Comment by MuhammedAlmaz** [comment]
Which component do you want touse it? From search or phoneInput ?

**Comment by SirPhemmiey** [comment]
Phone input. I actually want to implement sort of like an autosave onBlur

**Comment by SirPhemmiey** [comment]
@MuhammedAlmaz any luck with this, please?

**Comment by MuhammedAlmaz** [comment]
You can use **inputProps** props about it.
for example
```

inputProps={
onBlur:function(){console.log("test);}
}
```

**Comment by SirPhemmiey** [comment]
@MuhammedAlmaz , thank you. I'll try it. 

But i have one more question. 

How can in refill or populate the input field with a value.

Thank you very much

**Comment by SirPhemmiey** [comment]
@MuhammedAlmaz ?

**Comment by SirPhemmiey** [comment]
@MuhammedAlmaz
