### ISSUE TITLE
how long until it relfects to yarn and npm

### ISSUE THREAD

**Issue by RicardoBrito1938** [MuhammedAlmaz/React-Native-INTL-Phone-Input#27]
Hello, sorry if that is a silly question, i would like to know if i submit a PR and you accept it, how long does it take to reflect on yarn or npm? i see a PR accepted that is not reflecting when i run yarn add...

**Comment by MuhammedAlmaz** [comment]
What is your package version ?

**Comment by RicardoBrito1938** [comment]
it is 
    "react-native-intl-phone-input": "^1.2.19",

**Comment by RicardoBrito1938** [comment]
i see there was a recent change for Brazil's mask, but when i install the lib, i see countries.js for Brazil like:
  { ru:"Бразилия",lt:"Brazilija",tr:"Brezilya", en: 'Brazil',flag: '🇧🇷',code: 'BR', dialCode: '+55', mask: '999 9999' },
instead of 
  { ru:"Бразилия",lt:"Brazilija",tr:"Brezilya", en: 'Brazil',flag: '🇧🇷',code: 'BR', dialCode: '+55', mask: '(99) 99999 9999' },

**Comment by RicardoBrito1938** [comment]
Hello, any update on this issue?

**Comment by MuhammedAlmaz** [comment]
its adding on **1.2.21** version

**Comment by RicardoBrito1938** [comment]
awesome , thank you!!!
