### ISSUE TITLE
How can I set a default value to the field? 

### ISSUE THREAD

**Issue by ahmedsu** [MuhammedAlmaz/React-Native-INTL-Phone-Input#30]
I want to set a value for this field. Is there an option for that?

**Comment by MuhammedAlmaz** [comment]
check [#28 ](https://github.com/MuhammedAlmaz/React-Native-INTL-Phone-Input/issues/28) please

**Comment by MuhammedAlmaz** [comment]
check [#28](https://github.com/MuhammedAlmaz/React-Native-INTL-Phone-Input/issues/28) please
