### ISSUE TITLE
onendediting to detect user is done typing

### ISSUE THREAD

**Issue by sfarkas1988** [MuhammedAlmaz/React-Native-INTL-Phone-Input#35]
Any chance to integrate onendediting so we are able to detect that the user has finished editing this input type?

https://reactnative.dev/docs/textinput#onendediting

**Comment by fukemy** [comment]
any solution for user start typing?

**Comment by MuhammedAlmaz** [comment]
Hello i miss this issue idk how it possible :) So you can use inputProps this prop about this function. For example.

```typescript
<IntlPhoneInput
        inputProps={onEndEditing:()=>alert("ended")}
        ref={(ref) => this.phoneInput = ref}
        customModal={this.renderCustomModal}
        defaultCountry="TR"
        lang="TR"
      />
```
