### ISSUE TITLE
Add Custom Mask

### ISSUE THREAD

**Issue by whysetiawan** [MuhammedAlmaz/React-Native-INTL-Phone-Input#36]
Because some mask's formats are incorrect, Can you add a prop that provide the developer add custom mask?

Thank you @MuhammedAlmaz

**Comment by MuhammedAlmaz** [comment]
@whysetiawan , 
Yes mate, i will add it on next version.

**Comment by SirPhemmiey** [comment]
Hey bro @whysetiawan , is the new version that has this update out yet?

**Comment by MuhammedAlmaz** [comment]
Done #49
