### ISSUE TITLE
Change placeholderTextColor

### ISSUE THREAD

**Issue by vapstor** [MuhammedAlmaz/React-Native-INTL-Phone-Input#42]
According to the docs:
![Captura de tela de 2020-08-06 16-09-30](https://user-images.githubusercontent.com/15200187/89572258-44da2200-d7ff-11ea-9a9e-00840b2a34d4.png)

but when i'm trying to set the placeholder text color:

`phoneInputStyle={{ fontSize: 16, placeholderTextColor:'rgba(255, 255, 255, 0.8)', color: "#FFF" }}`

this happens:
![Captura de tela de 2020-08-06 16-08-12](https://user-images.githubusercontent.com/15200187/89574063-eebaae00-d801-11ea-8c2d-c2d736ed8e70.png)

**Comment by saenzjuan** [comment]
Still not working.

**Comment by MuhammedAlmaz** [comment]
Merged PR #42
