### ISSUE TITLE
Cuba and Uruguay code are wrong

### ISSUE THREAD

**Issue by dfalcon-rua** [MuhammedAlmaz/React-Native-INTL-Phone-Input#55]
The code of Cuba and Uruguay are wrong.
Cuba: +53 99 999 999
Uruguay: +598 99 999 999

**Comment by MuhammedAlmaz** [comment]
Done Thanks. Commit: https://github.com/MuhammedAlmaz/React-Native-INTL-Phone-Input/commit/b17840104eabc6b67a08b2cd3a6b7a81ae3af7cc
