### ISSUE TITLE
country name in search is case sensitive 

### ISSUE THREAD

**Issue by anasalaqeel** [MuhammedAlmaz/React-Native-INTL-Phone-Input#56]
country name in search is case sensitive, which means the user will not found the country if he not using the first letter in uppercase. 
it should be not case sensitive.

**Comment by darajava** [comment]
This is an issue for me too. Have you found a workaround?

**Comment by anasalaqeel** [comment]
@darajava   I make a pull request that fixing the issue but he does not replay anyone seems like he gave up

**Comment by MuhammedAlmaz** [comment]
PR Accepted
